Drop user reporttracker CASCADE;
CREATE USER reporttracker IDENTIFIED BY reporttracker ACCOUNT UNLOCK;
GRANT CONNECT, RESOURCE,CTXAPP, DBA TO reporttracker; commit;


CREATE TABLE IF NOT EXISTS CUTSOMER (
  CUTSOMER_ID INT NOT NULL,
  CUTSOMER_NAME VARCHAR(45) NULL,
  ADDRESS VARCHAR(45) NULL,
  PHONE_NUMBER BIGINT NOT NULL,
  EMAIL_ID VARCHAR(45) NULL,
  MODEL VARCHAR(45) NULL,
  SUFFIX VARCHAR(45) NULL,
  ICROP_NUMBER VARCHAR(45) NULL,
  PURPOSE VARCHAR(45) NULL,
  SO VARCHAR(45) NULL,
  TL VARCHAR(45) NULL,
  PRIMARY KEY (CUTSOMER_ID),
  UNIQUE INDEX PHONE_NUMBER_UNIQUE (PHONE_NUMBER ASC))

CREATE TABLE IF NOT EXISTS USER (
  USER_ID INT NOT NULL,
  ROLE VARCHAR(45) NULL,
  PASSWORD VARCHAR(45) NULL,
  PRIMARY KEY (USER_ID))


CREATE TABLE IF NOT EXISTS ENQUIRY (
  ENQUIRY_ID INT NOT NULL,
  ENQUIRY VARCHAR(100) NOT NULL,
  SO VARCHAR(45) NULL,
  TEAM VARCHAR(45) NULL,
  DATE DATETIME NULL,
  MODEL VARCHAR(45) NULL,
  DEALER_ID INT NULL,
  COLOUR VARCHAR(45) NULL,
  SUFFIX VARCHAR(45) NULL,
  MODE VARCHAR(45) NULL,
  SOURCE VARCHAR(45) NULL,
  PHONE_NUMBER BIGINT NOT NULL,
  CATEGORY VARCHAR(45) NULL,
  STATUS VARCHAR(45) NULL,
  ENGINE VARCHAR(45) NULL,
  PRIMARY KEY (ENQUIRY_ID),
  UNIQUE INDEX ENQUIRY_UNIQUE (ENQUIRY ASC),
  INDEX PHONE_FK_idx (PHONE_NUMBER ASC),
  INDEX DEALER_ID_FK_idx(DEALER_ID ASC),
  CONSTRAINT PHONE_FK
    FOREIGN KEY (PHONE_NUMBER)
    REFERENCES CUTSOMER (PHONE_NUMBER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,	
  CONSTRAINT DEALER_ID_FK
    FOREIGN KEY (DEALER_ID)
    REFERENCES DEALER (DEALER_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)


CREATE TABLE IF NOT EXISTS TEST_DRIVE (
  TEST_DRIVE_ID INT NOT NULL,
  ENQUIRY VARCHAR(45) NOT NULL,
  DEALER_ID INT NULL,
  MODEL VARCHAR(45) NULL,
  DRIVING_LICENCE VARCHAR(45) NULL,
  SO VARCHAR(45) NULL,
  DATE VARCHAR(45) NULL,
  REMARKS VARCHAR(45) NULL,
  PRIMARY KEY (TEST_DRIVE_ID),
  INDEX ENQUIRY_FK_idx (ENQUIRY ASC),
  INDEX DEALER_ID_FK_idx(DEALER_ID ASC),
  CONSTRAINT ENQUIRY_FK
    FOREIGN KEY (ENQUIRY)
    REFERENCES ENQUIRY (ENQUIRY)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT DEALER_ID_FK1
  FOREIGN KEY (DEALER_ID)
  REFERENCES DEALER (DEALER_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)



CREATE TABLE IF NOT EXISTS ENQUIRY_FOLLOWUP (
  ENQUIRY_FOLLOWUP_ID INT NOT NULL,
  ENQUIRY VARCHAR(45) NOT NULL,
  ENQUIRY_FOLLOW_UP_DATE DATETIME NULL,
  REMARKS VARCHAR(100) NULL,
  PRIMARY KEY (ENQUIRY_FOLLOWUP_ID),
  INDEX ENQUIRY_FK_idx (ENQUIRY ASC),
  CONSTRAINT ENQUIRY_FK1
    FOREIGN KEY (ENQUIRY)
    REFERENCES ENQUIRY (ENQUIRY)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



CREATE TABLE IF NOT EXISTS ORDER_BOOKING (
  ORDER_BOOKING_ID INT NOT NULL,
  ENQUIRY VARCHAR(45) NOT NULL,
  MODEL VARCHAR(45) NULL,
  ENGINE VARCHAR(45) NULL,
  FUEL VARCHAR(45) NULL,
  DEALER_ID INT NULL,
  DATE DATETIME NULL,
  PRIMARY KEY (ORDER_BOOKING_ID),
  INDEX ENQUIRY_FK_idx (ENQUIRY ASC),
  INDEX DEALER_ID_FK_idx(DEALER_ID ASC),
  CONSTRAINT ENQUIRY_FK2
    FOREIGN KEY (ENQUIRY)
    REFERENCES ENQUIRY (ENQUIRY)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT DEALER_ID_FK2
    FOREIGN KEY (DEALER_ID)
    REFERENCES DEALER (DEALER_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



CREATE TABLE IF NOT EXISTS INVOICE(
  INVOICE_ID INT NOT NULL,
  ENQUIRY VARCHAR(45) NOT NULL,
  INVOICE_DATE DATETIME NULL,
  INVOICE_GENERATE INT NULL,
  DEALER_ID INT NULL,
  PRIMARY KEY (INVOICE_ID),
  INDEX ENQUIRY_FK_idx (ENQUIRY ASC),
  INDEX DEALER_ID_FK_idx(DEALER_ID ASC),
  CONSTRAINT ENQUIRY_FK3
    FOREIGN KEY (ENQUIRY)
    REFERENCES ENQUIRY (ENQUIRY)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT DEALER_ID_FK3
    FOREIGN KEY (DEALER_ID)
    REFERENCES DEALER (DEALER_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

	
CREATE TABLE IF NOT EXISTS DEALER (
  DEALER_ID INT NOT NULL,
  DEALER_NAME VARCHAR(45) NOT NULL,
  ADDRESS VARCHAR(45) NULL,
  PRIMARY KEY (DEALER_ID))
  


SET FOREIGN_KEY_CHECKS=0;
drop table CUTSOMER;
drop table ENQUIRY;
drop table INVOICE;
SET FOREIGN_KEY_CHECKS=1;
  
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(1,"ENQ1",1,9999999999);
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(2,"ENQ2",1,9999999999);
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(3,"ENQ3",2,9999999999);
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(4,"ENQ4",2,9999999999);
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(5,"ENQ5",2,9999999999);
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(6,"ENQ6",3,9999999999);
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(7,"ENQ7",3,9999999999);
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(8,"ENQ8",4,9999999999);
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(9,"ENQ9",4,9999999999);
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(10,"ENQ10",4,9999999999);
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(11,"ENQ11",4,9999999999);
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(12,"ENQ12",4,9999999999);
INSERT INTO ENQUIRY(ENQUIRY_ID,ENQUIRY,DEALER_ID,PHONE_NUMBER) values(13,"ENQ13",4,9999999999);


INSERT INTO TEST_DRIVE(TEST_DRIVE_ID,ENQUIRY,DEALER_ID) values(1,"ENQ1",1);
INSERT INTO TEST_DRIVE(TEST_DRIVE_ID,ENQUIRY,DEALER_ID) values(2,"ENQ2",1);
INSERT INTO TEST_DRIVE(TEST_DRIVE_ID,ENQUIRY,DEALER_ID) values(3,"ENQ4",2);
INSERT INTO TEST_DRIVE(TEST_DRIVE_ID,ENQUIRY,DEALER_ID) values(4,"ENQ5",2);
INSERT INTO TEST_DRIVE(TEST_DRIVE_ID,ENQUIRY,DEALER_ID) values(5,"ENQ7",3);
INSERT INTO TEST_DRIVE(TEST_DRIVE_ID,ENQUIRY,DEALER_ID) values(6,"ENQ8",4);
INSERT INTO TEST_DRIVE(TEST_DRIVE_ID,ENQUIRY,DEALER_ID) values(7,"ENQ9",4);
INSERT INTO TEST_DRIVE(TEST_DRIVE_ID,ENQUIRY,DEALER_ID) values(8,"ENQ10",4);
INSERT INTO TEST_DRIVE(TEST_DRIVE_ID,ENQUIRY,DEALER_ID) values(9,"ENQ11",4);


INSERT INTO ORDER_BOOKING(ORDER_BOOKING_ID,ENQUIRY,DEALER_ID) values(1,"ENQ1",1);
INSERT INTO ORDER_BOOKING(ORDER_BOOKING_ID,ENQUIRY,DEALER_ID) values(2,"ENQ4",2);
INSERT INTO ORDER_BOOKING(ORDER_BOOKING_ID,ENQUIRY,DEALER_ID) values(3,"ENQ7",3);
INSERT INTO ORDER_BOOKING(ORDER_BOOKING_ID,ENQUIRY,DEALER_ID) values(4,"ENQ8",4);
INSERT INTO ORDER_BOOKING(ORDER_BOOKING_ID,ENQUIRY,DEALER_ID) values(5,"ENQ9",4);
INSERT INTO ORDER_BOOKING(ORDER_BOOKING_ID,ENQUIRY,DEALER_ID) values(6,"ENQ11",4);


INSERT INTO INVOICE(INVOICE_ID,ENQUIRY,DEALER_ID) values(1,"ENQ1",1);
INSERT INTO INVOICE(INVOICE_ID,ENQUIRY,DEALER_ID) values(2,"ENQ4",2);
INSERT INTO INVOICE(INVOICE_ID,ENQUIRY,DEALER_ID) values(3,"ENQ9",4);
INSERT INTO INVOICE(INVOICE_ID,ENQUIRY,DEALER_ID) values(4,"ENQ11",4);


1	Harsha Toyota, Near Hi-tech City	Hyderabad
2	Harsha Toyota, Malleshwari Complex	Hyderabad
3	Harsha Toyota, Hydernagar	R R District
4	Harsha Toyota, Madras Road	Kadapa